-- Generated by scripts/gen-lessons-sql.mjs
insert into public.lessons (id, level, unit, unit_title, sort, title, summary, duration_min, is_free) values
  ('n5-u1-l1', 'N5', 1, 'Scripts & sounds', 0, 'Hiragana part 1: あ–な rows', 'The first 25 hiragana, vowel sounds and how Japanese syllables work.', 25, true),
  ('n5-u1-l2', 'N5', 1, 'Scripts & sounds', 1, 'Hiragana part 2 & special sounds', 'The remaining hiragana, dakuten (が), small っ and long vowels.', 30, false),
  ('n5-u1-l3', 'N5', 1, 'Scripts & sounds', 2, 'Katakana & loanwords', 'All katakana and how English words become Japanese.', 30, false),
  ('n5-u2-l1', 'N5', 2, 'First conversations', 0, 'はじめまして — self-introduction', 'Introduce yourself: name, country, job, with です.', 25, false),
  ('n5-u2-l2', 'N5', 2, 'First conversations', 1, 'これ・それ・あれ — this and that', 'Pointing words, の for possession, asking “what is this?”.', 25, false),
  ('n5-u2-l3', 'N5', 2, 'First conversations', 2, 'Numbers, time and prices', 'Counting, telling the time and asking いくらですか.', 30, false),
  ('n5-u3-l1', 'N5', 3, 'Daily life verbs', 0, 'ます-form verbs', 'Present, past and negative polite verbs for daily routines.', 30, false),
  ('n5-u3-l2', 'N5', 3, 'Daily life verbs', 1, 'Particles を・に・で・へ', 'Objects, destinations, places of action and means.', 30, false),
  ('n5-u3-l3', 'N5', 3, 'Daily life verbs', 2, 'Adjectives い and な', 'Describing people and things, positive and negative.', 25, false),
  ('n5-u4-l1', 'N5', 4, 'Getting around', 0, 'あります・います — existence', 'Saying where things and people are.', 25, false),
  ('n5-u4-l2', 'N5', 4, 'Getting around', 1, '〜たいです and invitations', 'Wanting to do things and inviting friends.', 25, false),
  ('n5-u4-l3', 'N5', 4, 'Getting around', 2, 'N5 review & mock test', 'Timed practice across vocabulary, grammar, reading and listening.', 45, false),
  ('n4-u1-l1', 'N4', 1, 'Verb forms', 0, 'て-form mastery', 'Building て-form and using it to connect actions.', 30, true),
  ('n4-u1-l2', 'N4', 1, 'Verb forms', 1, 'Plain (dictionary) form', 'Casual speech and the plain forms of verbs and adjectives.', 30, false),
  ('n4-u1-l3', 'N4', 1, 'Verb forms', 2, 'Potential form', 'Saying what you can and can''t do.', 25, false),
  ('n4-u2-l1', 'N4', 2, 'Giving reasons & opinions', 0, 'から・ので — because', 'Giving reasons politely and casually.', 25, false),
  ('n4-u2-l2', 'N4', 2, 'Giving reasons & opinions', 1, '〜と思います', 'Sharing opinions and guesses.', 25, false),
  ('n4-u2-l3', 'N4', 2, 'Giving reasons & opinions', 2, '〜たことがあります', 'Talking about experiences.', 25, false),
  ('n4-u3-l1', 'N4', 3, 'Requests & permission', 0, '〜てもいいですか・〜てはいけません', 'Asking and giving permission.', 25, false),
  ('n4-u3-l2', 'N4', 3, 'Requests & permission', 1, '〜なければなりません', 'Obligation and things you must do.', 25, false),
  ('n4-u3-l3', 'N4', 3, 'Requests & permission', 2, 'Giving & receiving: あげる・もらう・くれる', 'Who gives what to whom.', 30, false),
  ('n4-u4-l1', 'N4', 4, 'Conditionals & review', 0, '〜たら・〜ば・〜と', 'The three main conditionals and when to use each.', 35, false),
  ('n4-u4-l2', 'N4', 4, 'Conditionals & review', 1, 'Passive and causative basics', 'Being done to, and making someone do something.', 35, false),
  ('n4-u4-l3', 'N4', 4, 'Conditionals & review', 2, 'N4 review & mock test', 'Timed practice across all sections.', 50, false),
  ('n3-u1-l1', 'N3', 1, 'Nuance in grammar', 0, '〜ように・〜ために', 'Purpose with volitional and non-volitional verbs.', 30, true),
  ('n3-u1-l2', 'N3', 1, 'Nuance in grammar', 1, '〜ばかり・〜ところ', 'Just did, about to do, only doing.', 30, false),
  ('n3-u1-l3', 'N3', 1, 'Nuance in grammar', 2, '〜せいで・〜おかげで', 'Positive and negative causes.', 25, false),
  ('n3-u2-l1', 'N3', 2, 'Reading real Japanese', 0, 'Notices and signs', 'Understanding everyday written information.', 30, false),
  ('n3-u2-l2', 'N3', 2, 'Reading real Japanese', 1, 'Short articles', 'Skimming and scanning newspaper-style texts.', 35, false),
  ('n3-u2-l3', 'N3', 2, 'Reading real Japanese', 2, 'Emails and messages', 'Reading and replying to polite messages.', 30, false),
  ('n3-u3-l1', 'N3', 3, 'Listening at natural speed', 0, 'Task-based listening', 'Getting the key information from conversations.', 30, false),
  ('n3-u3-l2', 'N3', 3, 'Listening at natural speed', 1, 'Casual speech patterns', 'Contractions and how Japanese is really spoken.', 30, false),
  ('n3-u3-l3', 'N3', 3, 'Listening at natural speed', 2, 'Keigo in listening', 'Recognising respectful and humble speech.', 30, false),
  ('n3-u4-l1', 'N3', 4, 'Exam strategy', 0, 'Vocabulary in context', 'Choosing words by nuance and collocation.', 30, false),
  ('n3-u4-l2', 'N3', 4, 'Exam strategy', 1, 'Timed reading strategy', 'Managing time across reading tasks.', 35, false),
  ('n3-u4-l3', 'N3', 4, 'Exam strategy', 2, 'N3 review & mock test', 'Full timed practice with feedback.', 55, false),
  ('n2-u1-l1', 'N2', 1, 'Advanced grammar', 0, '〜にわたって・〜をめぐって', 'Formal grammar for scope and dispute.', 30, true),
  ('n2-u1-l2', 'N2', 1, 'Advanced grammar', 1, '〜に反して・〜に基づいて', 'Contrast and basis in formal writing.', 30, false),
  ('n2-u1-l3', 'N2', 1, 'Advanced grammar', 2, '〜からすれば・〜にしろ', 'Viewpoint and concession patterns.', 30, false),
  ('n2-u2-l1', 'N2', 2, 'Workplace Japanese', 0, 'Business keigo', '尊敬語 and 謙譲語 in real workplace situations.', 35, false),
  ('n2-u2-l2', 'N2', 2, 'Workplace Japanese', 1, 'Emails and reports', 'Structure and set phrases for business writing.', 35, false),
  ('n2-u2-l3', 'N2', 2, 'Workplace Japanese', 2, 'Meetings and calls', 'Participating, agreeing and disagreeing politely.', 35, false),
  ('n2-u3-l1', 'N2', 3, 'Reading & listening', 0, 'Opinion articles', 'Following an argument and the writer''s view.', 35, false),
  ('n2-u3-l2', 'N2', 3, 'Reading & listening', 1, 'News listening', 'Understanding news at natural speed.', 35, false),
  ('n2-u3-l3', 'N2', 3, 'Reading & listening', 2, 'Integrated comprehension', 'Comparing two texts on the same topic.', 35, false),
  ('n2-u4-l1', 'N2', 4, 'Exam preparation', 0, 'Kanji and vocabulary drills', 'High-frequency N2 kanji compounds.', 30, false),
  ('n2-u4-l2', 'N2', 4, 'Exam preparation', 1, 'Timed full sections', 'Section-by-section timed practice.', 45, false),
  ('n2-u4-l3', 'N2', 4, 'Exam preparation', 2, 'N2 review & mock test', 'Full mock test with analysis.', 60, false),
  ('n1-u1-l1', 'N1', 1, 'Literary & formal grammar', 0, '〜をよそに・〜を皮切りに', 'Advanced connective expressions.', 35, true),
  ('n1-u1-l2', 'N1', 1, 'Literary & formal grammar', 1, '〜といえども・〜ならでは', 'Concession and uniqueness.', 35, false),
  ('n1-u1-l3', 'N1', 1, 'Literary & formal grammar', 2, '〜をもって・〜なくしては', 'Means, timing and necessity.', 35, false),
  ('n1-u2-l1', 'N1', 2, 'Complex reading', 0, 'Editorials and essays', 'Abstract argument and implication.', 40, false),
  ('n1-u2-l2', 'N1', 2, 'Complex reading', 1, 'Academic texts', 'Logical structure and technical vocabulary.', 40, false),
  ('n1-u2-l3', 'N1', 2, 'Complex reading', 2, 'Literature excerpts', 'Nuance, style and register.', 40, false),
  ('n1-u3-l1', 'N1', 3, 'Advanced listening', 0, 'Lectures and talks', 'Note-taking and main-point extraction.', 40, false),
  ('n1-u3-l2', 'N1', 3, 'Advanced listening', 1, 'Debates and discussions', 'Following multiple speakers and positions.', 40, false),
  ('n1-u3-l3', 'N1', 3, 'Advanced listening', 2, 'Implied meaning', 'What speakers mean but don''t say.', 35, false),
  ('n1-u4-l1', 'N1', 4, 'Exam mastery', 0, 'N1 vocabulary nuance', 'Near-synonyms and formal expressions.', 35, false),
  ('n1-u4-l2', 'N1', 4, 'Exam mastery', 1, 'Speed reading strategy', 'Finishing long passages in time.', 40, false),
  ('n1-u4-l3', 'N1', 4, 'Exam mastery', 2, 'N1 review & mock test', 'Full mock test with detailed feedback.', 70, false)
on conflict (id) do update set unit = excluded.unit, unit_title = excluded.unit_title, sort = excluded.sort,
  title = excluded.title, summary = excluded.summary, duration_min = excluded.duration_min, is_free = excluded.is_free;

insert into public.lesson_assets (lesson_id, notes) values
  ('n5-u1-l1', '## What you''ll learn
The first five rows of hiragana (25 characters) and the five vowel sounds that every Japanese syllable is built on.

## The five vowels
あ (a) · い (i) · う (u) · え (e) · お (o) — short and clear, like "ah, ee, oo, eh, oh".

## Rows in this lesson
- あ row: あ い う え お
- か row: か き く け こ
- さ row: さ し す せ そ (note: し = shi)
- た row: た ち つ て と (note: ち = chi, つ = tsu)
- な row: な に ぬ ね の

## Practice
1. Write each row five times, saying it aloud.
2. Read these words: あい (love), いえ (house), かさ (umbrella), ねこ (cat), すし (sushi).
3. Use the hiragana chart on this site and tap each character to check your pronunciation.

## Tip
Learn one row a day and review the previous rows before starting a new one.'),
  ('n5-u1-l2', '## What this lesson covers
The remaining hiragana, dakuten (が), small っ and long vowels.

## Focus point
Hiragana part 2 & special sounds — part of *Scripts & sounds* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u1-l3', '## What this lesson covers
All katakana and how English words become Japanese.

## Focus point
Katakana & loanwords — part of *Scripts & sounds* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u2-l1', '## What this lesson covers
Introduce yourself: name, country, job, with です.

## Focus point
**はじめまして — self-introduction** — part of *First conversations* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u2-l2', '## What this lesson covers
Pointing words, の for possession, asking “what is this?”.

## Focus point
**これ・それ・あれ — this and that** — part of *First conversations* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u2-l3', '## What this lesson covers
Counting, telling the time and asking いくらですか.

## Focus point
Numbers, time and prices — part of *First conversations* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u3-l1', '## What this lesson covers
Present, past and negative polite verbs for daily routines.

## Focus point
**ます-form verbs** — part of *Daily life verbs* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u3-l2', '## What this lesson covers
Objects, destinations, places of action and means.

## Focus point
**Particles を・に・で・へ** — part of *Daily life verbs* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u3-l3', '## What this lesson covers
Describing people and things, positive and negative.

## Focus point
**Adjectives い and な** — part of *Daily life verbs* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u4-l1', '## What this lesson covers
Saying where things and people are.

## Focus point
**あります・います — existence** — part of *Getting around* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u4-l2', '## What this lesson covers
Wanting to do things and inviting friends.

## Focus point
**〜たいです and invitations** — part of *Getting around* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n5-u4-l3', '## What this lesson covers
Timed practice across vocabulary, grammar, reading and listening.

## Focus point
N5 review & mock test — part of *Getting around* in the JLPT N5 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N5 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u1-l1', '## What you''ll learn
How to make the て-form of any verb and use it to connect actions: "I woke up, ate breakfast and went to work."

## The rules
- う・つ・る verbs → って: かう → かって, まつ → まって, とる → とって
- む・ぶ・ぬ verbs → んで: のむ → のんで, あそぶ → あそんで
- く → いて, ぐ → いで: かく → かいて, およぐ → およいで
- す → して: はなす → はなして
- る-verbs → drop る + て: たべる → たべて
- Irregular: する → して, くる → きて, いく → いって

## Connecting actions
あさ おきて、ごはんを たべて、かいしゃへ いきました。
(I got up in the morning, ate, and went to the office.)

## Practice
Make the て-form: よむ, まつ, みる, いく, べんきょうする.'),
  ('n4-u1-l2', '## What this lesson covers
Casual speech and the plain forms of verbs and adjectives.

## Focus point
Plain (dictionary) form — part of *Verb forms* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u1-l3', '## What this lesson covers
Saying what you can and can''t do.

## Focus point
Potential form — part of *Verb forms* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u2-l1', '## What this lesson covers
Giving reasons politely and casually.

## Focus point
**から・ので — because** — part of *Giving reasons & opinions* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u2-l2', '## What this lesson covers
Sharing opinions and guesses.

## Focus point
**〜と思います** — part of *Giving reasons & opinions* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u2-l3', '## What this lesson covers
Talking about experiences.

## Focus point
**〜たことがあります** — part of *Giving reasons & opinions* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u3-l1', '## What this lesson covers
Asking and giving permission.

## Focus point
**〜てもいいですか・〜てはいけません** — part of *Requests & permission* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u3-l2', '## What this lesson covers
Obligation and things you must do.

## Focus point
**〜なければなりません** — part of *Requests & permission* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u3-l3', '## What this lesson covers
Who gives what to whom.

## Focus point
**Giving & receiving: あげる・もらう・くれる** — part of *Requests & permission* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u4-l1', '## What this lesson covers
The three main conditionals and when to use each.

## Focus point
**〜たら・〜ば・〜と** — part of *Conditionals & review* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u4-l2', '## What this lesson covers
Being done to, and making someone do something.

## Focus point
Passive and causative basics — part of *Conditionals & review* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n4-u4-l3', '## What this lesson covers
Timed practice across all sections.

## Focus point
N4 review & mock test — part of *Conditionals & review* in the JLPT N4 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N4 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u1-l1', '## What you''ll learn
The difference between 〜ように and 〜ために — both mean "so that / in order to".

## The key rule
- ために: the verb is something you **control** (volitional).
  日本で働くために、日本語を勉強しています。
- ように: the verb is something you **can''t directly control** (non-volitional, potential, negative).
  日本語が話せるように、毎日練習しています。
  忘れないように、メモします。

## Quick check
- 上手に なる → ように (you can''t force "becoming good")
- 留学する → ために (a deliberate action)

## Practice
Choose ように or ために:
1. 試験に合格する___、毎日勉強する。
2. 風邪をひかない___、手を洗う。'),
  ('n3-u1-l2', '## What this lesson covers
Just did, about to do, only doing.

## Focus point
**〜ばかり・〜ところ** — part of *Nuance in grammar* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u1-l3', '## What this lesson covers
Positive and negative causes.

## Focus point
**〜せいで・〜おかげで** — part of *Nuance in grammar* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u2-l1', '## What this lesson covers
Understanding everyday written information.

## Focus point
Notices and signs — part of *Reading real Japanese* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u2-l2', '## What this lesson covers
Skimming and scanning newspaper-style texts.

## Focus point
Short articles — part of *Reading real Japanese* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u2-l3', '## What this lesson covers
Reading and replying to polite messages.

## Focus point
Emails and messages — part of *Reading real Japanese* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u3-l1', '## What this lesson covers
Getting the key information from conversations.

## Focus point
Task-based listening — part of *Listening at natural speed* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u3-l2', '## What this lesson covers
Contractions and how Japanese is really spoken.

## Focus point
Casual speech patterns — part of *Listening at natural speed* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u3-l3', '## What this lesson covers
Recognising respectful and humble speech.

## Focus point
Keigo in listening — part of *Listening at natural speed* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u4-l1', '## What this lesson covers
Choosing words by nuance and collocation.

## Focus point
Vocabulary in context — part of *Exam strategy* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u4-l2', '## What this lesson covers
Managing time across reading tasks.

## Focus point
Timed reading strategy — part of *Exam strategy* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n3-u4-l3', '## What this lesson covers
Full timed practice with feedback.

## Focus point
N3 review & mock test — part of *Exam strategy* in the JLPT N3 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N3 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u1-l1', '## What you''ll learn
Two formal grammar patterns common in news and reports: 〜にわたって (over a span) and 〜をめぐって (concerning / over a dispute).

## 〜にわたって
Used with time or space to show the whole extent.
3日間にわたって会議が行われた。 — The meeting was held over three days.

## 〜をめぐって
Used when there is debate or conflict about something.
新しい法律をめぐって、議論が続いている。 — Debate continues over the new law.

## Common mistakes
Don''t use をめぐって for simple "about" — use について there.

## Practice
Complete: 全国___、雨が降った。 / 予算___、意見が分かれた。'),
  ('n2-u1-l2', '## What this lesson covers
Contrast and basis in formal writing.

## Focus point
**〜に反して・〜に基づいて** — part of *Advanced grammar* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u1-l3', '## What this lesson covers
Viewpoint and concession patterns.

## Focus point
**〜からすれば・〜にしろ** — part of *Advanced grammar* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u2-l1', '## What this lesson covers
尊敬語 and 謙譲語 in real workplace situations.

## Focus point
Business keigo — part of *Workplace Japanese* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u2-l2', '## What this lesson covers
Structure and set phrases for business writing.

## Focus point
Emails and reports — part of *Workplace Japanese* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u2-l3', '## What this lesson covers
Participating, agreeing and disagreeing politely.

## Focus point
Meetings and calls — part of *Workplace Japanese* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u3-l1', '## What this lesson covers
Following an argument and the writer''s view.

## Focus point
Opinion articles — part of *Reading & listening* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u3-l2', '## What this lesson covers
Understanding news at natural speed.

## Focus point
News listening — part of *Reading & listening* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u3-l3', '## What this lesson covers
Comparing two texts on the same topic.

## Focus point
Integrated comprehension — part of *Reading & listening* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u4-l1', '## What this lesson covers
High-frequency N2 kanji compounds.

## Focus point
Kanji and vocabulary drills — part of *Exam preparation* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u4-l2', '## What this lesson covers
Section-by-section timed practice.

## Focus point
Timed full sections — part of *Exam preparation* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n2-u4-l3', '## What this lesson covers
Full mock test with analysis.

## Focus point
N2 review & mock test — part of *Exam preparation* in the JLPT N2 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N2 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u1-l1', '## What you''ll learn
〜をよそに (ignoring, in disregard of) and 〜を皮切りに (starting with) — two expressions you''ll meet in N1 reading.

## 〜をよそに
Doing something while ignoring others'' feelings or a situation.
親の心配をよそに、彼は一人で旅に出た。

## 〜を皮切りに
The first in a series of events.
東京公演を皮切りに、全国ツアーが始まる。

## Nuance
をよそに has a slightly critical tone; を皮切りに is neutral and common in news.

## Practice
Write one sentence with each pattern about your own life or work.'),
  ('n1-u1-l2', '## What this lesson covers
Concession and uniqueness.

## Focus point
**〜といえども・〜ならでは** — part of *Literary & formal grammar* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u1-l3', '## What this lesson covers
Means, timing and necessity.

## Focus point
**〜をもって・〜なくしては** — part of *Literary & formal grammar* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u2-l1', '## What this lesson covers
Abstract argument and implication.

## Focus point
Editorials and essays — part of *Complex reading* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u2-l2', '## What this lesson covers
Logical structure and technical vocabulary.

## Focus point
Academic texts — part of *Complex reading* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u2-l3', '## What this lesson covers
Nuance, style and register.

## Focus point
Literature excerpts — part of *Complex reading* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u3-l1', '## What this lesson covers
Note-taking and main-point extraction.

## Focus point
Lectures and talks — part of *Advanced listening* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u3-l2', '## What this lesson covers
Following multiple speakers and positions.

## Focus point
Debates and discussions — part of *Advanced listening* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u3-l3', '## What this lesson covers
What speakers mean but don''t say.

## Focus point
Implied meaning — part of *Advanced listening* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u4-l1', '## What this lesson covers
Near-synonyms and formal expressions.

## Focus point
N1 vocabulary nuance — part of *Exam mastery* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u4-l2', '## What this lesson covers
Finishing long passages in time.

## Focus point
Speed reading strategy — part of *Exam mastery* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.'),
  ('n1-u4-l3', '## What this lesson covers
Full mock test with detailed feedback.

## Focus point
N1 review & mock test — part of *Exam mastery* in the JLPT N1 syllabus.

## How to study this lesson
1. Listen to the lecture above (or read this page) once all the way through without pausing.
2. Go through it again, saying each Japanese example out loud.
3. Close the page and try to explain the point in your own words.
4. Test yourself with the N1 practice quiz for this unit.

## Practice
Write two of your own example sentences using today''s point, then check them with your teacher in the next live class or the Speaking Lab.')
on conflict (lesson_id) do update set notes = excluded.notes;
