import type { Skill } from "@/lib/learning";

// Questions used only by the course tests in the Learn menu. None of these appear in any other quiz on the site.
export type Row = [Skill, string, string[], number, string, string?];

export const courseBanks: Record<string, Record<string, Row[]>> = {
  japanese: {
    starter: [
      ["Vocabulary", "「ほん」 means:", ["Book", "Pen", "Bag", "Desk"], 0, "ほん (本) = book."],
      ["Vocabulary", "「でんわ」 means:", ["Telephone", "Television", "Electricity", "Train"], 0, "でんわ (電話) = telephone."],
      ["Grammar", "これは わたし ___ かばんです。", ["の", "を", "が", "で"], 0, "の links nouns: わたしのかばん = my bag."],
      ["Vocabulary", "「あさごはん」 is:", ["Breakfast", "Lunch", "Dinner", "A snack"], 0, "あさ (morning) + ごはん (meal) = breakfast."],
      ["Kanji", "「口」 means:", ["Mouth", "Eye", "Ear", "Hand"], 0, "口 (くち) = mouth."],
      ["Grammar", "わたしは まいにち コーヒー ___ のみます。", ["を", "に", "へ", "は"], 0, "を marks the object: drink coffee."],
      ["Vocabulary", "「ともだち」 means:", ["Friend", "Teacher", "Family", "Neighbour"], 0, "ともだち (友達) = friend."],
      ["Reading", "「スーパーは 9じから 9じまでです。」 When is the supermarket open?", ["9 a.m. to 9 p.m.", "Only in the morning", "24 hours", "Closed today"], 0, "から = from, まで = until."],
      ["Vocabulary", "「しろい」 means:", ["White", "Black", "Red", "Yellow"], 0, "しろい (白い) = white."],
      ["Listening", "Listen and choose the meaning.", ["See you tomorrow", "Good morning", "Thank you", "I'm sorry"], 0, "また あした = see you tomorrow.", "また あした"],
    ],
    next: [
      ["Grammar", "雨が 降っている ___、出かけません。", ["から", "けど", "のに", "まで"], 0, "から = because: it's raining, so I won't go out."],
      ["Vocabulary", "「れんしゅう」 means:", ["Practice", "Exam", "Holiday", "Class"], 0, "れんしゅう (練習) = practice."],
      ["Grammar", "日本語を 勉強 ___ ために、日本へ 行きます。", ["する", "した", "して", "しない"], 0, "Dictionary form + ために = in order to."],
      ["Kanji", "How is 「電車」 read?", ["でんしゃ", "でんき", "じてんしゃ", "くるま"], 0, "電車 = でんしゃ (train)."],
      ["Vocabulary", "「べんり」 means:", ["Convenient", "Dangerous", "Expensive", "Quiet"], 0, "べんり (便利) = convenient."],
      ["Grammar", "この 本は 読み ___ です。(easy to read)", ["やすい", "にくい", "たい", "ながら"], 0, "〜やすい = easy to …"],
      ["Reading", "「明日の 授業は 休みです。」 What is the notice saying?", ["There is no class tomorrow", "Class starts early", "Class moved rooms", "Bring a textbook"], 0, "休み = day off / no class."],
      ["Vocabulary", "「じゅんび」 means:", ["Preparation", "Answer", "Plan", "Reason"], 0, "じゅんび (準備) = preparation."],
      ["Grammar", "テレビを 見 ___ ごはんを 食べます。(while)", ["ながら", "たら", "ても", "ので"], 0, "〜ながら = while doing."],
      ["Listening", "Listen. What does the speaker want?", ["To go to Kyoto next year", "To leave Kyoto", "To work in Kyoto now", "To teach in Kyoto"], 0, "行きたいと思っています = I'm thinking of going.", "来年、京都へ 行きたいと 思って います"],
    ],
  },
  beginner: {
    words: [
      ["Vocabulary", "「ねこ」 means:", ["Cat", "Dog", "Mouse", "Horse"], 0, "ねこ = cat."],
      ["Vocabulary", "「さかな」 means:", ["Fish", "Meat", "Egg", "Vegetable"], 0, "さかな = fish."],
      ["Vocabulary", "「おかあさん」 means:", ["Mother", "Father", "Sister", "Grandmother"], 0, "おかあさん = mother."],
      ["Vocabulary", "「がっこう」 means:", ["School", "Hospital", "Shop", "Station"], 0, "がっこう = school."],
      ["Vocabulary", "「あめ」 (weather) means:", ["Rain", "Snow", "Wind", "Cloud"], 0, "あめ = rain."],
      ["Vocabulary", "「て」 means:", ["Hand", "Foot", "Head", "Eye"], 0, "て = hand."],
      ["Vocabulary", "「おいしい」 means:", ["Tasty", "Hot", "Cold", "Sweet"], 0, "おいしい = delicious."],
      ["Vocabulary", "「いえ」 means:", ["House", "Room", "Door", "Garden"], 0, "いえ = house, home."],
      ["Vocabulary", "「あおい」 means:", ["Blue", "Green", "Purple", "Grey"], 0, "あおい = blue."],
      ["Listening", "Listen. What is it?", ["An apple", "A banana", "Bread", "Milk"], 0, "りんご = apple.", "りんご"],
    ],
  },
  grammar: {
    basic: [
      ["Grammar", "わたしは 学生 ___ ありません。", ["では", "が", "を", "に"], 0, "〜ではありません = am not."],
      ["Grammar", "この かさは だれ ___ ですか。", ["の", "が", "に", "を"], 0, "だれの = whose."],
      ["Grammar", "えきまで あるいて 10ぷん ___ かかります。", ["ぐらい", "まで", "から", "だけ"], 0, "ぐらい = about."],
      ["Grammar", "Choose the correct past form of 「たかい」.", ["たかかった", "たかいでした", "たかくた", "たかだった"], 0, "い-adjective past: drop い, add かった."],
      ["Grammar", "Choose the correct past form of 「しずか」 (な-adjective).", ["しずかでした", "しずかかった", "しずかいでした", "しずくでした"], 0, "な-adjectives: しずかでした."],
      ["Grammar", "にほんへ ___ ことが ありますか。", ["いった", "いく", "いって", "いき"], 0, "〜たことがある = have ever …"],
      ["Grammar", "へやに だれ ___ いません。", ["も", "が", "は", "を"], 0, "だれもいません = nobody is there."],
      ["Grammar", "あした あめが ふる ___ しれません。", ["かも", "ので", "から", "ても"], 0, "〜かもしれない = might."],
      ["Grammar", "The ない-form of 「のむ」 is:", ["のまない", "のみない", "のむない", "のめない"], 0, "う-verbs: change う-row to あ-row + ない."],
      ["Grammar", "せんせいに しつもんを ___ ください。", ["して", "する", "した", "しない"], 0, "て-form + ください = please do."],
    ],
    intermediate: [
      ["Grammar", "会議に 遅れない ___、早めに 出た。", ["ように", "ために", "ことに", "そうに"], 0, "〜ないように = so as not to."],
      ["Grammar", "読めば 読む ___、面白く なる。", ["ほど", "だけ", "まで", "ばかり"], 0, "〜ば〜ほど = the more …, the more …"],
      ["Grammar", "彼は 知って いる ___、何も 言わない。", ["くせに", "ために", "うちに", "ように"], 0, "〜くせに = even though (critical)."],
      ["Grammar", "若い ___ に、いろいろな 国へ 行きたい。", ["うち", "あいだ", "まま", "とき"], 0, "〜うちに = while still …"],
      ["Grammar", "窓を 開けた ___ 寝て しまった。", ["まま", "うちに", "ながら", "ばかり"], 0, "〜たまま = leaving it as it is."],
      ["Grammar", "Pick the passive form: 先生が 私を ほめた → 私は 先生に ___。", ["ほめられた", "ほめさせた", "ほめた", "ほめれた"], 0, "Passive of ほめる = ほめられる."],
      ["Grammar", "この 仕事は 私 ___ やらせて ください。", ["に", "を", "が", "で"], 0, "私にやらせてください = let me do it."],
      ["Grammar", "練習 ___ 、上手に ならない。", ["しなければ", "したら", "すると", "しても"], 0, "〜なければ = if (you) don't."],
      ["Grammar", "Choose the humble form of 「いきます」.", ["まいります", "いらっしゃいます", "おいでになります", "いかれます"], 0, "まいります is the humble form."],
      ["Grammar", "天気予報 ___ よると、明日は 晴れる そうだ。", ["に", "で", "を", "と"], 0, "〜によると = according to."],
    ],
  },
  vocabulary: {
    basic: [
      ["Vocabulary", "「くつ」 means:", ["Shoes", "Socks", "Hat", "Shirt"], 0, "くつ = shoes."],
      ["Vocabulary", "「やさい」 means:", ["Vegetables", "Fruit", "Meat", "Rice"], 0, "やさい = vegetables."],
      ["Vocabulary", "「いしゃ」 means:", ["Doctor", "Nurse", "Teacher", "Driver"], 0, "いしゃ (医者) = doctor."],
      ["Vocabulary", "「てがみ」 means:", ["Letter", "Paper", "Gloves", "Stamp"], 0, "てがみ (手紙) = letter."],
      ["Vocabulary", "「あつい」 (weather) means:", ["Hot", "Cold", "Warm", "Cool"], 0, "あつい = hot."],
      ["Vocabulary", "「かいもの」 means:", ["Shopping", "Cooking", "Cleaning", "Washing"], 0, "かいもの = shopping."],
      ["Vocabulary", "「ひだり」 means:", ["Left", "Right", "Front", "Back"], 0, "ひだり = left. みぎ = right."],
      ["Vocabulary", "「おとうと」 means:", ["Younger brother", "Older brother", "Younger sister", "Cousin"], 0, "おとうと = younger brother."],
      ["Vocabulary", "「なつ」 means:", ["Summer", "Winter", "Spring", "Autumn"], 0, "なつ = summer."],
      ["Vocabulary", "The opposite of 「ながい」 (long) is:", ["みじかい", "ひくい", "せまい", "うすい"], 0, "みじかい = short."],
    ],
    intermediate: [
      ["Vocabulary", "「ていねい」 means:", ["Polite / careful", "Rude", "Quick", "Lazy"], 0, "ていねい (丁寧) = polite, careful."],
      ["Vocabulary", "「たしかめる」 means:", ["To make sure", "To give up", "To forget", "To hide"], 0, "確かめる = to check, make sure."],
      ["Vocabulary", "「なつかしい」 means:", ["Nostalgic", "Embarrassing", "Annoying", "Lonely"], 0, "懐かしい = nostalgic."],
      ["Vocabulary", "「えんりょ」 means:", ["Holding back / reserve", "Distance", "Promise", "Invitation"], 0, "遠慮 = restraint, holding back."],
      ["Vocabulary", "「くやしい」 means:", ["Frustrated / vexed", "Happy", "Sleepy", "Proud"], 0, "悔しい = frustrating, vexing."],
      ["Vocabulary", "「ちょきん」 means:", ["Savings", "Debt", "Salary", "Tax"], 0, "貯金 = savings."],
      ["Vocabulary", "「うらやましい」 means:", ["Envious", "Grateful", "Shy", "Scary"], 0, "羨ましい = envious."],
      ["Vocabulary", "「せっかく」 means:", ["With much trouble / specially", "Suddenly", "Rarely", "Finally"], 0, "せっかく = taking the trouble; at last (an opportunity)."],
      ["Vocabulary", "「めんどう」 means:", ["Troublesome", "Interesting", "Simple", "Kind"], 0, "面倒 = troublesome, a hassle."],
      ["Vocabulary", "「しめきり」 means:", ["Deadline", "Holiday", "Entrance", "Discount"], 0, "締め切り = deadline."],
    ],
  },
  reading: {
    basic: [
      ["Reading", "「でぐち」 on a sign means:", ["Exit", "Entrance", "Toilet", "Ticket gate"], 0, "出口 (でぐち) = exit. 入口 = entrance."],
      ["Reading", "Which is written in katakana?", ["テレビ", "てれび", "手礼美", "てレび"], 0, "Loanwords like TV are written テレビ."],
      ["Reading", "How do you write “sushi” in hiragana?", ["すし", "すじ", "そし", "すい"], 0, "すし = sushi."],
      ["Reading", "「おんな」 (女) on a door means:", ["Women", "Men", "Staff", "Children"], 0, "女 = woman. 男 = man."],
      ["Reading", "「きんえん」 (禁煙) on a sign means:", ["No smoking", "Smoking area", "Closed", "Free"], 0, "禁煙 = no smoking."],
      ["Reading", "「やすみ」 written on a shop door means:", ["Closed today", "Open", "Sale", "New"], 0, "休み = closed / day off."],
      ["Reading", "Which word is “Tokyo” in kanji?", ["東京", "京都", "大阪", "日本"], 0, "東京 = Tokyo."],
      ["Reading", "「メニュー」 means:", ["Menu", "Money", "Memo", "Movie"], 0, "メニュー = menu."],
      ["Reading", "「わたしの へやは 2かいです。」 Where is the writer's room?", ["On the 2nd floor", "Room number 2", "Two rooms", "Second house"], 0, "2かい = second floor."],
      ["Reading", "How many strokes does 「十」 have?", ["2", "1", "3", "4"], 0, "十 is written in 2 strokes."],
    ],
    intermediate: [
      ["Reading", "「立入禁止」 on a sign means:", ["No entry", "Stand here", "Emergency exit", "Waiting area"], 0, "立入禁止 = keep out."],
      ["Reading", "「お一人様 一点限り」 at a sale means:", ["One per customer", "One-person table", "Single price", "Only today"], 0, "限り = limited to."],
      ["Reading", "「本日 貸切」 on a restaurant door means:", ["Reserved for a private party today", "Open late today", "Half price", "Under renovation"], 0, "貸切 = reserved / chartered."],
      ["Reading", "「〜様」 written after a name on an envelope is:", ["A polite title (Mr / Ms)", "The sender", "The postcode", "Urgent"], 0, "様 = polite title."],
      ["Reading", "「賞味期限」 on food means:", ["Best-before date", "Price", "Ingredients", "Weight"], 0, "賞味期限 = best before."],
      ["Reading", "「当日券 あり」 at a theatre means:", ["Same-day tickets available", "Sold out", "Members only", "No photos"], 0, "当日券 = same-day ticket."],
      ["Reading", "「工事中のため、迂回して ください」 What should you do?", ["Take a detour — construction", "Wait here", "Go faster", "Turn back home"], 0, "迂回 = detour."],
      ["Reading", "「乗り換え」 at a station means:", ["Transfer / change trains", "Exit", "Lost property", "Ticket office"], 0, "乗り換え = transfer."],
      ["Reading", "In a formal letter, 「拝啓」 is used:", ["At the start", "At the end", "For the date", "For the address"], 0, "拝啓 opens a formal letter; 敬具 closes it."],
      ["Reading", "「お手数ですが、ご記入 ください」 asks you to:", ["Please fill this in, sorry for the trouble", "Please wait", "Please pay", "Please sign later"], 0, "記入 = fill in."],
    ],
  },
  business: {
    keigo: [
      ["Speaking", "Answering the office phone, you say:", ["はい、ナツゴで ございます", "もしもし、だれ？", "はい、何？", "ナツゴだよ"], 0, "〜でございます is the formal company greeting."],
      ["Speaking", "A client asks for your manager, who is out. You say:", ["あいにく 田中は 外出して おります", "田中さんは いません", "田中さんは 遊んで います", "知りません"], 0, "Refer to your own colleague without さん, using おります."],
      ["Vocabulary", "「名刺」 means:", ["Business card", "Name tag", "Contract", "Invoice"], 0, "名刺 (めいし) = business card."],
      ["Vocabulary", "「打ち合わせ」 means:", ["A (planning) meeting", "A party", "A phone call", "A lunch"], 0, "打ち合わせ = meeting, discussion."],
      ["Speaking", "Leaving the office before colleagues, you say:", ["お先に 失礼します", "おつかれ", "さようなら、みんな", "いってきます"], 0, "お先に失礼します = excuse me for leaving first."],
      ["Grammar", "Respectful form of 「見る」 (for a client):", ["ご覧に なる", "拝見する", "見られる", "見せる"], 0, "ご覧になる is respectful; 拝見する is humble."],
      ["Grammar", "Humble form of 「言う」 (about yourself):", ["申す", "おっしゃる", "言われる", "言わせる"], 0, "申す is humble; おっしゃる is respectful."],
      ["Vocabulary", "「見積もり」 means:", ["Quotation / estimate", "Receipt", "Order", "Discount"], 0, "見積もり = quote, estimate."],
      ["Speaking", "Ending a business email, you write:", ["よろしく お願い いたします", "じゃあね", "以上だよ", "またね"], 0, "Standard polite closing."],
      ["Reading", "「至急 ご確認 ください」 in an email means:", ["Please check urgently", "No need to check", "Check next week", "Already checked"], 0, "至急 = urgent."],
    ],
  },
  work: {
    workplace: [
      ["Speaking", "Your first day at work. You introduce yourself and end with:", ["よろしく お願いします", "おやすみなさい", "いただきます", "おかえり"], 0, "よろしくお願いします = please treat me kindly."],
      ["Vocabulary", "「履歴書」 means:", ["Résumé / CV", "Passport", "Contract", "Payslip"], 0, "履歴書 (りれきしょ) = résumé."],
      ["Vocabulary", "「面接」 means:", ["Interview", "Training", "Salary", "Holiday"], 0, "面接 (めんせつ) = interview."],
      ["Vocabulary", "「残業」 means:", ["Overtime", "Day off", "Break", "Bonus"], 0, "残業 (ざんぎょう) = overtime."],
      ["Vocabulary", "「在留カード」 is:", ["Residence card", "Bank card", "Health card", "Train pass"], 0, "在留カード = residence card for foreign residents."],
      ["Speaking", "In an interview you're asked why you want to work in Japan. You begin:", ["日本の 技術に 興味が あるからです", "わかりません", "お金が ないです", "特に ありません"], 0, "Give a clear reason with 〜からです."],
      ["Vocabulary", "「給料」 means:", ["Salary", "Tax", "Rent", "Fee"], 0, "給料 (きゅうりょう) = salary."],
      ["Speaking", "You need to report a mistake to your boss. You start with:", ["申し訳 ありません、ミスが ありました", "ミス、ないです", "大丈夫です", "あとで 言います"], 0, "Apologise first, then report."],
      ["Vocabulary", "「有給休暇」 means:", ["Paid leave", "Sick note", "Unpaid work", "Business trip"], 0, "有給休暇 = paid holiday."],
      ["Reading", "「シフト表」 at work shows:", ["Your work schedule", "Your salary", "The menu", "The office map"], 0, "シフト表 = shift timetable."],
    ],
  },
  study: {
    campus: [
      ["Vocabulary", "「留学」 means:", ["Studying abroad", "Graduation", "Homework", "Entrance exam"], 0, "留学 (りゅうがく) = study abroad."],
      ["Vocabulary", "「授業料」 means:", ["Tuition fee", "Scholarship", "Textbook", "Library card"], 0, "授業料 = tuition."],
      ["Vocabulary", "「奨学金」 means:", ["Scholarship", "Loan", "Prize", "Fine"], 0, "奨学金 (しょうがくきん) = scholarship."],
      ["Vocabulary", "「寮」 means:", ["Dormitory", "Classroom", "Cafeteria", "Gym"], 0, "寮 (りょう) = dormitory."],
      ["Vocabulary", "「専攻」 means:", ["Major (subject)", "Teacher", "Semester", "Club"], 0, "専攻 (せんこう) = major."],
      ["Speaking", "You want to ask a professor a question after class. You begin:", ["先生、ちょっと よろしいでしょうか", "ねえ、先生", "おい", "先生、来て"], 0, "Polite way to get a teacher's attention."],
      ["Vocabulary", "「単位」 at university means:", ["Credit (for a course)", "Uniform", "Timetable", "Campus"], 0, "単位 (たんい) = academic credit."],
      ["Reading", "「休講」 on the notice board means:", ["Class cancelled", "Extra class", "Exam today", "Room change"], 0, "休講 = lecture cancelled."],
      ["Vocabulary", "「サークル」 at a Japanese university is:", ["A student club", "A ring road", "A lecture hall", "A test"], 0, "サークル = student club."],
      ["Speaking", "Asking a classmate to lend you their notes:", ["ノートを 貸して もらえない？", "ノートを くれ", "ノートは いらない", "ノートを 書いた"], 0, "〜てもらえない？ = could you … for me? (casual)."],
    ],
  },
  phrases: {
    everyday: [
      ["Speaking", "A shop clerk says 「いらっしゃいませ」. It means:", ["Welcome", "Goodbye", "Sorry", "Sold out"], 0, "いらっしゃいませ = welcome (to the shop)."],
      ["Speaking", "You want to say “It's okay / I'm fine”.", ["だいじょうぶです", "だめです", "ちがいます", "しりません"], 0, "大丈夫です = it's fine."],
      ["Speaking", "You want to say “I don't understand”.", ["わかりません", "しりません", "いりません", "できます"], 0, "わかりません = I don't understand."],
      ["Speaking", "You come home. What do you say?", ["ただいま", "いってきます", "おじゃまします", "いただきます"], 0, "ただいま = I'm home."],
      ["Speaking", "Entering someone's house, you say:", ["おじゃまします", "ただいま", "おかえり", "ごちそうさま"], 0, "おじゃまします = sorry to intrude."],
      ["Speaking", "Congratulating a friend, you say:", ["おめでとう", "ざんねん", "おだいじに", "すみません"], 0, "おめでとう = congratulations."],
      ["Speaking", "A friend is sick. You say:", ["おだいじに", "おめでとう", "いただきます", "おやすみ"], 0, "お大事に = take care (get well)."],
      ["Speaking", "You want to ask “Is it okay to use a card?”", ["カードで いいですか", "カードは なんですか", "カードを ください", "カードが あります"], 0, "〜でいいですか = is … okay?"],
      ["Listening", "Listen and choose the meaning.", ["Please wait a moment", "Please come in", "Please sit down", "Please hurry"], 0, "しょうしょう おまちください = please wait a moment.", "しょうしょう おまち ください"],
      ["Listening", "Listen and choose the meaning.", ["Cheers!", "Let's eat", "Good luck", "Welcome back"], 0, "かんぱい = cheers.", "かんぱい"],
    ],
  },
};
