import type { Skill } from "@/lib/learning";
import type { QuizLevel } from "@/lib/quizBank";

// Extra questions used only by the topic quizzes, so every level has at least ten per topic.
type Row = [Skill, string, string[], number, string, string?];

export const topicExtras: Record<QuizLevel, Row[]> = {
  N5: [
    ["Vocabulary", "「くるま」 means:", ["Train", "Car", "Bicycle", "Road"], 1, "くるま (車) = car. でんしゃ = train."],
    ["Vocabulary", "「あかい」 means:", ["Blue", "White", "Red", "Black"], 2, "あかい (赤い) = red. あおい = blue."],
    ["Kanji", "「月」 means:", ["Sun", "Moon / month", "Star", "Year"], 1, "月 = moon or month, as in 一月 (January)."],
    ["Kanji", "How is 「水」 read on its own?", ["みず", "ひ", "き", "つち"], 0, "水 = みず (water)."],
    ["Kanji", "「人」 means:", ["Person", "Tree", "Mouth", "Big"], 0, "人 (ひと) = person. 日本人 = Japanese person."],
    ["Kanji", "How is 「大きい」 read?", ["ちいさい", "おおきい", "たかい", "ながい"], 1, "大きい = おおきい (big). 小さい = ちいさい (small)."],
    ["Listening", "Listen and choose the meaning.", ["Thank you", "Excuse me / sorry", "Good night", "Welcome"], 1, "すみません = excuse me / sorry.", "すみません"],
    ["Listening", "Listen and choose the meaning.", ["Good evening", "Good morning", "Hello", "Goodbye"], 0, "こんばんは = good evening.", "こんばんは"],
    ["Listening", "Listen. What time is it?", ["3:00", "4:00", "7:00", "9:00"], 2, "しちじ = 7 o'clock.", "いま しちじです"],
    ["Listening", "Listen. What does the person want?", ["Water", "Tea", "Coffee", "Juice"], 1, "おちゃ = green tea.", "おちゃを ください"],
    ["Listening", "Listen. Where is the person going?", ["To school", "To the hospital", "To the station", "Home"], 0, "がっこう = school.", "がっこうへ いきます"],
    ["Listening", "Listen and choose the meaning.", ["Nice to meet you", "See you tomorrow", "Let's eat", "I'm home"], 0, "はじめまして = nice to meet you.", "はじめまして"],
    ["Listening", "Listen. How much is it?", ["100 yen", "300 yen", "500 yen", "1,000 yen"], 2, "ごひゃく えん = 500 yen.", "ごひゃく えんです"],
    ["Reading", "「きょうは にちようびです。」 What day is it today?", ["Saturday", "Sunday", "Monday", "Friday"], 1, "にちようび = Sunday."],
    ["Reading", "「わたしは ねこが すきです。」 What does the writer like?", ["Dogs", "Cats", "Fish", "Birds"], 1, "ねこ = cat. すき = like."],
    ["Reading", "「あした ともだちと えいがを みます。」 What will the writer do tomorrow?", ["Read a book", "Watch a film with a friend", "Go to school", "Cook dinner"], 1, "えいがを みます = watch a film."],
    ["Reading", "「この ペンは 100えんです。」 How much is the pen?", ["10 yen", "100 yen", "1,000 yen", "110 yen"], 1, "100えん = 100 yen."],
    ["Reading", "「へやに つくえと いすが あります。」 What is in the room?", ["A bed and a TV", "A desk and a chair", "A cat and a dog", "Nothing"], 1, "つくえ = desk, いす = chair."],
    ["Reading", "「わたしは インドから きました。」 Where is the writer from?", ["Japan", "India", "China", "America"], 1, "インドから きました = came from India."],
    ["Reading", "「ぎんこうは えきの まえに あります。」 Where is the bank?", ["Behind the station", "In front of the station", "Next to the school", "Inside the station"], 1, "まえ = in front of."],
    ["Reading", "「まいにち 8じかん ねます。」 How long does the writer sleep?", ["6 hours", "7 hours", "8 hours", "9 hours"], 2, "8じかん = 8 hours."],
    ["Vocabulary", "「くつした」 means:", ["Socks", "Shoes", "Gloves", "Scarf"], 0, "くつした = socks."],
    ["Vocabulary", "「せまい」 means:", ["Narrow / small (room)", "Wide", "Tall", "Heavy"], 0, "せまい = narrow, cramped. ひろい = spacious."],
    ["Grammar", "えいがを 見に ___。", ["いきます", "たべます", "ねます", "かきます"], 0, "〜に いく = go to do something."],
    ["Kanji", "「右」 means:", ["Right", "Left", "Up", "Down"], 0, "右 (みぎ) = right. 左 (ひだり) = left."],
    ["Kanji", "How is 「休み」 read?", ["やすみ", "きゅうみ", "やすむ", "よみ"], 0, "休み = やすみ (holiday, rest)."],
    ["Reading", "「あしたは しけんです。こんばん べんきょうします。」 What will the writer do tonight?", ["Study", "Watch TV", "Go out", "Sleep early"], 0, "べんきょうします = will study."],
    ["Reading", "「りんごを みっつ かいました。」 How many apples did the writer buy?", ["3", "1", "2", "6"], 0, "みっつ = three (things)."],
    ["Listening", "Listen. What is the weather?", ["It's raining", "It's sunny", "It's snowing", "It's windy"], 0, "あめが ふって います = it's raining.", "いま、あめが ふって います"],
    ["Listening", "Listen. Where is the toilet?", ["Upstairs", "Outside", "Next to the station", "On the left"], 0, "にかい = second floor (upstairs).", "トイレは にかいです"],
  ],
  N4: [
    ["Vocabulary", "「さいふ」 means:", ["Umbrella", "Wallet", "Watch", "Key"], 1, "さいふ (財布) = wallet."],
    ["Vocabulary", "「けしき」 means:", ["Scenery", "Weather", "Season", "Map"], 0, "けしき (景色) = scenery, view."],
    ["Vocabulary", "「たのしみ」 means:", ["Worry", "Something to look forward to", "Problem", "Hobby"], 1, "たのしみ (楽しみ) = looking forward to."],
    ["Vocabulary", "「こしょう」 (故障) means:", ["Breakdown / out of order", "Pepper", "Accident", "Repair"], 0, "故障 = breakdown. 故障中 = out of order."],
    ["Kanji", "How is 「病院」 read?", ["びょういん", "びよういん", "びょうき", "いいん"], 0, "病院 = びょういん (hospital). 美容院 = びよういん (beauty salon)."],
    ["Kanji", "「旅行」 means:", ["Travel", "Work", "Study", "Meal"], 0, "旅行 (りょこう) = travel, trip."],
    ["Kanji", "How is 「始まる」 read?", ["はじまる", "おわる", "とまる", "きまる"], 0, "始まる = はじまる (to begin). 終わる = おわる (to end)."],
    ["Kanji", "「意味」 means:", ["Opinion", "Meaning", "Interest", "Reason"], 1, "意味 (いみ) = meaning."],
    ["Kanji", "How is 「家族」 read?", ["かぞく", "いえぞく", "かじょく", "けぞく"], 0, "家族 = かぞく (family)."],
    ["Listening", "Listen. What does the speaker want to do?", ["Go to Japan someday", "Live in Japan now", "Leave Japan", "Teach Japanese"], 0, "いつか〜たい = want to … someday.", "いつか にほんへ いきたいです"],
    ["Listening", "Listen. What is the problem?", ["Lost their wallet", "Lost their phone", "Missed the train", "Forgot homework"], 0, "さいふを なくしました = lost my wallet.", "さいふを なくして しまいました"],
    ["Listening", "Listen. What is allowed?", ["Taking photos", "Eating", "Smoking", "Running"], 0, "しゃしんを とっても いいです = you may take photos.", "ここで しゃしんを とっても いいですよ"],
    ["Listening", "Listen. When does the shop close?", ["8 p.m.", "9 p.m.", "10 p.m.", "It doesn't close"], 1, "くじ = 9 o'clock.", "みせは よる くじに しまります"],
    ["Listening", "Listen. How does the person feel?", ["They have a cold", "They are hungry", "They are happy", "They are bored"], 0, "かぜを ひきました = caught a cold.", "かぜを ひいて しまいました"],
    ["Listening", "Listen. What should you not do?", ["Speak loudly", "Sit down", "Drink water", "Read"], 0, "おおきい こえで はなさないで = don't speak loudly.", "おおきい こえで はなさないで ください"],
    ["Listening", "Listen. What did the person do on the weekend?", ["Cleaned the room", "Went shopping", "Met friends", "Slept all day"], 0, "へやを そうじしました = cleaned the room.", "しゅうまつは へやを そうじしました"],
    ["Reading", "「明日は 雨が 降るそうです。かさを 持って 行きましょう。」 What is the advice?", ["Take an umbrella", "Stay home", "Wear a coat", "Leave early"], 0, "かさを持って行きましょう = let's take an umbrella."],
    ["Reading", "「田中さんは 歌が 上手です。」 What is true about Tanaka-san?", ["Good at singing", "Bad at singing", "Likes dancing", "Teaches music"], 0, "上手 (じょうず) = skilful."],
    ["Reading", "「図書館では 静かに して ください。」 What does this mean?", ["Please be quiet in the library", "The library is closed", "Books are free", "Please read aloud"], 0, "静かにしてください = please be quiet."],
    ["Reading", "「会議は 午後 2時から 3時まで です。」 How long is the meeting?", ["30 minutes", "1 hour", "2 hours", "3 hours"], 1, "2時から3時まで = from 2 to 3."],
    ["Reading", "「この 道を まっすぐ 行くと、右に 駅が あります。」 Where is the station?", ["Straight on, on the right", "Behind you", "On the left, turn back", "Across the river"], 0, "まっすぐ = straight, 右 = right."],
    ["Reading", "「日本へ 来る 前に、少し 日本語を 勉強しました。」 When did the writer study Japanese?", ["Before coming to Japan", "After arriving", "Never", "Every day in Japan"], 0, "来る前に = before coming."],
    ["Reading", "「弟は 私より 背が 高いです。」 Who is taller?", ["The writer", "The younger brother", "They are the same", "The older sister"], 1, "AはBより高い = A is taller than B."],
    ["Vocabulary", "「おつり」 means:", ["Change (money)", "Receipt", "Price", "Coin purse"], 0, "おつり = change given back."],
    ["Vocabulary", "「ねぼう」 means:", ["Oversleeping", "Insomnia", "Nap", "Dream"], 0, "ねぼう (寝坊) = oversleeping."],
    ["Kanji", "How is 「洗う」 read?", ["あらう", "あらわす", "せんう", "あそぶ"], 0, "洗う = あらう (wash)."],
    ["Kanji", "「急行」 on a train board means:", ["Express", "Local", "Last train", "Delayed"], 0, "急行 (きゅうこう) = express train."],
    ["Reading", "「お湯を 入れて 3分 待って ください。」 What are these instructions for?", ["Making instant noodles or similar", "Washing clothes", "Taking medicine", "Charging a phone"], 0, "お湯 = hot water, 3分待つ = wait 3 minutes."],
    ["Reading", "「駐輪場は 駅の 北口に あります。」 Where can you park a bicycle?", ["At the station's north exit", "Inside the station", "At the south exit", "Nowhere"], 0, "駐輪場 = bicycle parking, 北口 = north exit."],
    ["Listening", "Listen. What does the person ask you to do?", ["Write your name here", "Pay now", "Sit down", "Come back later"], 0, "名前を 書いて ください = please write your name.", "ここに 名前を 書いて ください"],
    ["Listening", "Listen. Why can't the person come?", ["They have work", "They are sick", "They have no money", "They forgot"], 0, "仕事が あるので = because I have work.", "すみません、仕事が あるので 行けません"],
  ],
  N3: [
    ["Vocabulary", "「さっそく」 means:", ["At once", "Slowly", "Rarely", "Finally"], 0, "さっそく (早速) = straight away."],
    ["Vocabulary", "「ゆずる」 means:", ["To hand over / give up (a seat)", "To refuse", "To borrow", "To hide"], 0, "席をゆずる = give up one's seat."],
    ["Vocabulary", "「ためらう」 means:", ["To hesitate", "To hurry", "To agree", "To forget"], 0, "ためらう = to hesitate."],
    ["Kanji", "How is 「相談」 read?", ["そうだん", "そうたん", "しょうだん", "あいだん"], 0, "相談 = そうだん (consultation, talk over)."],
    ["Kanji", "「確認」 means:", ["Confirmation", "Permission", "Refusal", "Introduction"], 0, "確認 (かくにん) = confirmation, checking."],
    ["Kanji", "How is 「届ける」 read?", ["とどける", "とどまる", "あずける", "うける"], 0, "届ける = とどける (deliver)."],
    ["Kanji", "「募集」 means:", ["Recruitment", "Collection of taxes", "Cancellation", "Training"], 0, "募集 (ぼしゅう) = recruitment, call for applicants."],
    ["Listening", "Listen. What does the speaker mean?", ["I'll try, but I can't promise", "Definitely yes", "Absolutely not", "I already did it"], 0, "やってみますが、約束はできません.", "やって みますが、約束は できません"],
    ["Listening", "Listen. Why is the speaker late?", ["Overslept", "Traffic jam", "Train accident", "Was sick"], 0, "寝坊しました = overslept.", "すみません、寝坊して しまいました"],
    ["Listening", "Listen. What is the speaker asking?", ["Could you lend me a pen?", "Where is the pen?", "Is this your pen?", "Buy me a pen"], 0, "貸していただけませんか = could you lend me…?", "ペンを 貸して いただけませんか"],
    ["Listening", "Listen. What does the speaker decide?", ["To stop eating sweets", "To eat more sweets", "To open a shop", "To bake a cake"], 0, "〜ことにしました = decided to …", "甘い ものを 食べない ことに しました"],
    ["Listening", "Listen. What is the weather like?", ["It looks like it will rain", "It is sunny", "It snowed", "It is windy"], 0, "降りそう = looks like it will fall.", "今にも 雨が 降りそうですね"],
    ["Listening", "Listen. What happened?", ["The meeting was postponed to next week", "The meeting is today", "The meeting was cancelled forever", "The meeting moved rooms"], 0, "延期 = postponed.", "会議は 来週に 延期に なりました"],
    ["Listening", "Listen. What does the speaker recommend?", ["Booking early", "Going without a reservation", "Calling later", "Choosing another hotel"], 0, "早めに予約したほうがいい.", "早めに 予約した ほうが いいですよ"],
    ["Reading", "「駅前の 店は 毎週 水曜日が 休みです。」 When is the shop closed?", ["Every Wednesday", "Every weekend", "Mondays only", "Never"], 0, "毎週水曜日 = every Wednesday."],
    ["Reading", "「このアプリを 使えば、電車の 遅れが すぐ わかります。」 What does the app do?", ["Shows train delays quickly", "Sells tickets", "Books hotels", "Translates"], 0, "遅れ = delay."],
    ["Reading", "「参加費は 無料ですが、事前に 申し込みが 必要です。」 What is required?", ["Registering in advance", "Paying a fee", "Bringing food", "Nothing"], 0, "事前に申し込みが必要 = advance registration needed."],
    ["Reading", "「最近、忙しくて 運動する 時間が ありません。」 What is the writer's problem?", ["No time to exercise", "Too much free time", "An injury", "No money"], 0, "運動する時間がない."],
    ["Reading", "「ゴミは 決められた 曜日の 朝 8時までに 出して ください。」 What is the rule?", ["Put rubbish out by 8 a.m. on set days", "Any time", "Only at night", "Keep rubbish inside"], 0, "決められた曜日 = designated days."],
    ["Reading", "「彼は 約束を 守る 人だから、きっと 来ますよ。」 Why will he come?", ["He keeps his promises", "He is nearby", "He is free today", "He was forced"], 0, "約束を守る = keep a promise."],
    ["Reading", "「雨の ため、明日の 運動会は 中止に なりました。」 What happened?", ["Sports day was cancelled due to rain", "Sports day moved indoors", "It will be held as planned", "It was postponed one hour"], 0, "中止 = cancellation."],
    ["Vocabulary", "「あいかわらず」 means:", ["As usual / as ever", "Suddenly", "For the first time", "Rarely"], 0, "相変わらず = as always."],
    ["Vocabulary", "「ぐっすり」 describes:", ["Sleeping soundly", "Eating fast", "Running hard", "Crying loudly"], 0, "ぐっすり寝る = sleep soundly."],
    ["Grammar", "雨が 降り ___ だから、傘を 持って いこう。", ["そう", "よう", "らしい", "みたい"], 0, "Stem + そう = looks like it will …"],
    ["Kanji", "How is 「現在」 read?", ["げんざい", "けんざい", "げんさい", "いまざい"], 0, "現在 = げんざい (at present)."],
    ["Kanji", "「割引」 means:", ["Discount", "Division", "Refund", "Tax"], 0, "割引 (わりびき) = discount."],
    ["Reading", "「当日の キャンセルは 料金の 50%を いただきます。」 What happens if you cancel on the day?", ["You pay half the fee", "Full refund", "No charge", "You pay double"], 0, "50%をいただきます = we charge 50%."],
    ["Reading", "「エレベーター 点検中。階段を ご利用 ください。」 What should you do?", ["Use the stairs", "Wait for the lift", "Call staff", "Leave the building"], 0, "点検中 = under inspection."],
    ["Listening", "Listen. What does the speaker want to know?", ["Whether the shop is open tomorrow", "The shop's address", "The price", "The owner's name"], 0, "明日も 開いて いますか = are you open tomorrow too?", "明日も 開いて いますか"],
    ["Listening", "Listen. What happened to the speaker?", ["Their phone broke", "They lost their keys", "They missed the bus", "They got a new job"], 0, "壊れて しまった = ended up broken.", "スマホが 壊れて しまったんです"],
  ],
  N2: [
    ["Vocabulary", "「たやすい」 means:", ["Easy", "Expensive", "Dangerous", "Tiring"], 0, "たやすい = easy, simple."],
    ["Vocabulary", "「見通し」 means:", ["Outlook / prospect", "Mistake", "Inspection", "Glasses"], 0, "見通し (みとおし) = outlook, forecast."],
    ["Vocabulary", "「手間」 means:", ["Time and effort", "Hand size", "Gloves", "Handicraft"], 0, "手間がかかる = takes time and effort."],
    ["Kanji", "How is 「把握」 read?", ["はあく", "はかく", "ばあく", "はにぎ"], 0, "把握 = はあく (grasp, understand)."],
    ["Kanji", "「削減」 means:", ["Reduction / cut", "Increase", "Addition", "Calculation"], 0, "削減 (さくげん) = reduction."],
    ["Kanji", "How is 「怠る」 read?", ["おこたる", "なまける", "たいる", "おこる"], 0, "怠る = おこたる (neglect)."],
    ["Kanji", "「範囲」 means:", ["Range / scope", "Example", "Boundary wall", "Average"], 0, "範囲 (はんい) = range, scope."],
    ["Listening", "Listen. What is the speaker's view?", ["It's not that it's impossible", "It's completely impossible", "It's easy", "It's already done"], 0, "〜ないこともない = it's not that … not.", "できない ことも ないですね"],
    ["Listening", "Listen. What will happen to the price?", ["It will go up from next month", "It will fall", "It stays the same", "It is free"], 0, "値上げ = price increase.", "来月から 値上げ される そうです"],
    ["Listening", "Listen. What is the speaker doing?", ["Declining an invitation politely", "Accepting gladly", "Inviting someone", "Complaining"], 0, "せっかくですが = kind of you, but…", "せっかくですが、今回は 遠慮 させて いただきます"],
    ["Listening", "Listen. What does the speaker regret?", ["Not studying harder", "Studying too much", "Changing jobs", "Moving house"], 0, "〜ばよかった = should have …", "もっと 勉強して おけば よかったです"],
    ["Listening", "Listen. What is the instruction?", ["Submit the report by Friday", "Read the report", "Delete the report", "Print it on Monday"], 0, "金曜日までに提出.", "報告書は 金曜日までに 提出して ください"],
    ["Listening", "Listen. What is the speaker saying?", ["Depending on the weather, the event may be cancelled", "The event is indoors", "The event is certain", "The event was yesterday"], 0, "天候によっては = depending on the weather.", "天候に よっては、中止に なる 場合が あります"],
    ["Listening", "Listen. How was the result?", ["Better than expected", "Worse than expected", "As expected", "Not announced"], 0, "思ったより = more than I thought.", "結果は 思ったより よかったです"],
    ["Reading", "「本日の 説明会は 定員に 達した ため、受付を 終了 しました。」 Why did registration close?", ["It reached capacity", "It was cancelled", "The time passed", "The speaker is ill"], 0, "定員に達した = reached capacity."],
    ["Reading", "「経費削減の 一環として、紙の 資料を 廃止します。」 What is changing?", ["Paper documents are being dropped to cut costs", "More printing", "New office", "Higher salaries"], 0, "一環として = as part of."],
    ["Reading", "「彼の 意見は もっともだが、現実的 とは 言い難い。」 What does the writer think?", ["Reasonable, but hardly realistic", "Totally wrong", "Perfect", "Too cheap"], 0, "言い難い = hard to say."],
    ["Reading", "「お問い合わせの 際は、注文 番号を ご用意 ください。」 What should you prepare?", ["Your order number", "Your passport", "Cash", "A photo"], 0, "注文番号 = order number."],
    ["Reading", "「少子化に 伴い、地方の 学校が 次々と 閉校 している。」 What is happening?", ["Rural schools are closing as births fall", "Schools are growing", "Teachers are striking", "Cities are emptying"], 0, "に伴い = along with."],
    ["Reading", "「この 薬は 効き目が 強い 反面、副作用も ある。」 What is said about the drug?", ["Strong effect, but side effects too", "No effect", "Completely safe", "Cheap"], 0, "反面 = on the other hand."],
    ["Reading", "「締め切り間際に なって 慌てる ことの ない よう、計画的に 進めよう。」 What is the advice?", ["Work to a plan so you don't panic near the deadline", "Wait until the deadline", "Ignore deadlines", "Work only at night"], 0, "間際 = just before."],
    ["Vocabulary", "「さりげない」 means:", ["Casual / unobtrusive", "Rude", "Obvious", "Painful"], 0, "さりげない = nonchalant, subtle."],
    ["Vocabulary", "「目安」 means:", ["Rough guide / standard", "Eye drops", "Target market", "Discount"], 0, "目安 (めやす) = guideline, rough estimate."],
    ["Grammar", "経験が ない ___、彼は 一番 上手だった。", ["わりに", "ために", "せいで", "うえで"], 0, "〜わりに = considering, for (someone with no experience)."],
    ["Kanji", "How is 「派遣」 read?", ["はけん", "はかん", "ぱけん", "はつけん"], 0, "派遣 = はけん (dispatch; temp staffing)."],
    ["Kanji", "「拡大」 means:", ["Expansion / enlargement", "Reduction", "Repair", "Delay"], 0, "拡大 (かくだい) = expansion."],
    ["Reading", "「応募者多数の 場合は、抽選と させて いただきます。」 What happens if many apply?", ["A lottery decides", "First come, first served", "Everyone is accepted", "The event is cancelled"], 0, "抽選 = lottery, draw."],
    ["Reading", "「ご利用 いただいた 時間に 応じて 料金が 変わります。」 What does the price depend on?", ["How long you use it", "Your age", "The day of the week", "Nothing: it's fixed"], 0, "に応じて = according to."],
    ["Listening", "Listen. What is the speaker suggesting?", ["Postponing the decision until next week", "Deciding now", "Cancelling the project", "Asking the client"], 0, "見送る = put off.", "結論は 来週まで 見送りましょう"],
    ["Listening", "Listen. How does the speaker feel about the result?", ["Disappointed it fell short", "Very satisfied", "Surprised it was so good", "Indifferent"], 0, "物足りない = not quite satisfying.", "結果は 正直 物足りないですね"],
  ],
  N1: [
    ["Vocabulary", "「いたわる」 means:", ["To treat with care", "To scold", "To ignore", "To compete"], 0, "いたわる = take care of, be kind to."],
    ["Vocabulary", "「目論見」 means:", ["Plan / scheme", "Eyesight", "Review", "Catalogue"], 0, "目論見 (もくろみ) = plan, intention."],
    ["Vocabulary", "「おざなり」 means:", ["Perfunctory / half-hearted", "Careful", "Elegant", "Generous"], 0, "おざなり = done for form's sake."],
    ["Kanji", "How is 「脆弱」 read?", ["ぜいじゃく", "きじゃく", "ぜいよわ", "もろじゃく"], 0, "脆弱 = ぜいじゃく (fragile, vulnerable)."],
    ["Kanji", "How is 「憤る」 read?", ["いきどおる", "ふんる", "おこたる", "いかる"], 0, "憤る = いきどおる (be indignant)."],
    ["Kanji", "「斡旋」 means:", ["Mediation / placement", "Rotation", "Refusal", "Celebration"], 0, "斡旋 (あっせん) = mediation, arranging (e.g. a job)."],
    ["Kanji", "How is 「捗る」 read?", ["はかどる", "はかる", "すすむ", "ちょくる"], 0, "捗る = はかどる (make progress)."],
    ["Listening", "Listen. What does the speaker imply?", ["It's not something to laugh about", "It's very funny", "Let's laugh together", "I didn't hear"], 0, "笑い事ではない = no laughing matter.", "笑いごとでは 済まされませんよ"],
    ["Listening", "Listen. What is the speaker's attitude?", ["Will do it no matter what", "Might give up", "Refuses", "Doesn't care"], 0, "何が何でも = no matter what.", "何が 何でも やり遂げる つもりです"],
    ["Listening", "Listen. What is being announced?", ["The president will step down at the end of the term", "A new hire", "A product launch", "A holiday"], 0, "退任 = step down.", "社長は 任期満了を もって 退任 いたします"],
    ["Listening", "Listen. What does the speaker mean?", ["Since it came to this, there's no choice but to do it", "Let's stop", "I'll think tomorrow", "It's not my job"], 0, "〜からには = now that …", "こう なった からには、やる しか ありません"],
    ["Listening", "Listen. How does the speaker describe the plan?", ["Hardly feasible", "Very easy", "Already finished", "Brilliant"], 0, "〜難い = hard to …", "その 計画は 実現 し難いと 思います"],
    ["Listening", "Listen. What is the speaker apologising for?", ["The delay in replying", "Breaking something", "Being rude", "Arriving early"], 0, "返信が遅くなり = reply was late.", "ご返信が 遅く なり、誠に 申し訳 ございません"],
    ["Listening", "Listen. What is the speaker saying?", ["Even an expert can make mistakes", "Experts never err", "I'm an expert", "Mistakes are rare"], 0, "猿も木から落ちる.", "猿も 木から 落ちる と いいますからね"],
    ["Reading", "「当局は、事態の 収束を 待って 正式な 見解を 示す 方針だ。」 What will the authorities do?", ["Give an official view once things settle", "Speak immediately", "Stay silent forever", "Resign"], 0, "収束 = settling down."],
    ["Reading", "「彼の 功績は 枚挙に いとまが ない。」 What does this mean?", ["His achievements are too many to count", "He has none", "They are forgotten", "They are disputed"], 0, "枚挙にいとまがない = too numerous to list."],
    ["Reading", "「技術の 進歩と 相まって、在宅勤務が 急速に 普及した。」 What helped remote work spread?", ["Combined with advances in technology", "New laws only", "Lower rent", "Bad weather"], 0, "と相まって = combined with."],
    ["Reading", "「彼の 発言は 誤解を 招きかねない。」 What is the concern?", ["His remark could cause misunderstanding", "He spoke clearly", "He refused to talk", "He apologised"], 0, "〜かねない = might well …"],
    ["Reading", "「予算の 制約 ゆえ、計画の 縮小は やむを得ない。」 Why is the plan being cut?", ["Budget constraints", "Lack of staff", "Bad weather", "Public opposition"], 0, "ゆえ = because of."],
    ["Reading", "「一概に 悪いとは 言えない が、改善の 余地は ある。」 What is the writer's opinion?", ["Not simply bad, but there is room for improvement", "Completely bad", "Perfect", "Should be abolished"], 0, "一概に〜とは言えない = can't say flatly."],
    ["Reading", "「事故の 原因は 究明 されて おらず、再発 防止策も 講じられて いない。」 What is the situation?", ["The cause is unknown and no prevention steps are in place", "The case is solved", "Prevention is complete", "No accident occurred"], 0, "究明 = investigation, 講じる = take measures."],
    ["Vocabulary", "「ひたむき」 means:", ["Single-minded / earnest", "Lazy", "Arrogant", "Cowardly"], 0, "ひたむき = devoted, earnest."],
    ["Vocabulary", "「辛辣」 means:", ["Harsh / scathing", "Spicy food", "Gentle", "Delicious"], 0, "辛辣 (しんらつ) = scathing (criticism)."],
    ["Grammar", "彼の 才能は 誰もが 認める ___ だ。", ["ところ", "もの", "わけ", "こと"], 0, "誰もが認めるところだ = it is something everyone acknowledges."],
    ["Kanji", "How is 「僅か」 read?", ["わずか", "きんか", "すこしか", "かすか"], 0, "僅か = わずか (only a little)."],
    ["Kanji", "「遵守」 means:", ["Compliance / observance", "Defence", "Rejection", "Retirement"], 0, "遵守 (じゅんしゅ) = compliance (e.g. with rules)."],
    ["Reading", "「本件は 社外秘につき、取り扱いには 十分 ご注意 ください。」 What is the warning?", ["It's confidential: handle with care", "It's public", "It's been deleted", "It's urgent to share"], 0, "社外秘 = confidential within the company."],
    ["Reading", "「需要の 回復を 見込んで、生産 体制を 強化する 方針だ。」 What is the company doing?", ["Strengthening production, expecting demand to recover", "Cutting production", "Closing factories", "Ignoring demand"], 0, "見込んで = anticipating."],
    ["Listening", "Listen. What is the speaker's stance?", ["They can't overlook the issue", "They will ignore it", "They agree fully", "They are confused"], 0, "見過ごす わけには いかない = can't let it pass.", "この 問題を 見過ごす わけには いきません"],
    ["Listening", "Listen. What does the speaker request?", ["Your frank opinion", "Your silence", "Payment", "A written apology"], 0, "忌憚のない ご意見 = candid opinions.", "忌憚の ない ご意見を お聞かせ ください"],
  ],
};
